[package]
name = "envsync"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
clap = {version = "4.0.29", features = ["derive"]}

[dev-dependencies]
assert_cmd = "2.0.7"
predicates = "2.1.4"
pretty_assertions = "1.3.0"
